### ISSUE TITLE
Unable to get the date first avaliable

### ISSUE THREAD

**Issue by Virajdatt** [VishalBilagi/amazon-review-scrapper#2]
Seeing this error when I run the code!
@VishalBilagi 

https://www.amazon.in/Bulls-Bears-Other-Beasts-Indian/dp/9382616217/ref=sr_1_1?ie=UTF8
Traceback (most recent call last):
  File "./src/scrap.py", line 138, in <module>
    getReviewData()
  File "./src/scrap.py", line 59, in getReviewData
    dateFirstAvaliable = parse(str(soup.find(class_="date-first-available").contents[1].contents[0])).strftime("%d/%m/%Y")
AttributeError: 'NoneType' object has no attribute 'contents' # #

**Comment by VishalBilagi** [comment]
HTML content for a product that is a book is different from one that isn't, that's why the scrapper code fails.

Will rectify this soon.
