### ISSUE TITLE
Persmissions to push to the repo amazon-review-scrapper

### ISSUE THREAD

**Issue by Virajdatt** [VishalBilagi/amazon-review-scrapper#3]
Permission Denied!!!

I am also not able to assign u this issue!!!

virajdatt-MacBook-Pro:amazon-review-scrapper virajdattkohir$ git push  origin master 
remote: Permission to VishalBilagi/amazon-review-scrapper.git denied to Virajdatt.
fatal: unable to access 'https://github.com/VishalBilagi/amazon-review-scrapper/': The requested URL returned error: 403
virajdatt-MacBook-Pro:amazon-review-scrapper virajdattkohir$ git push  origin master 
remote: Permission to VishalBilagi/amazon-review-scrapper.git denied to Virajdatt.
fatal: unable to access 'https://github.com/VishalBilagi/amazon-review-scrapper/': The requested URL returned error: 403

**Comment by VishalBilagi** [comment]
Go to [settings](https://github.com/VishalBilagi/amazon-review-scrapper/invitations) of the repo and you'll have an invitation to collaborate
